sudo: required

language: node_js

node_js:
  - "8"

cache:
    directories:
      - node_modules

env:
  global:
    - CI=false

script:
  - echo "npm test temporarily disabled"

install:
  - npm install

after_success:
  - docker --version

deploy:
  - provider: script
    script: npm run build
    on:
      branch: develop
    skip_cleanup: true

  - provider: script
    script: npm run build-development
    on:
      branch: develop
    skip_cleanup: true

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: ropsten-tx-debugger.knstats.com
    region: ap-southeast-1
    acl: public_read
    local_dir: build
    skip_cleanup: true
    on:
      branch: develop

  - provider: script
    script: npm run build-production
    on:
      branch: develop
    skip_cleanup: true

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: mainnet-tx-debugger.knstats.com
    region: ap-southeast-1
    acl: public_read
    local_dir: build
    skip_cleanup: true
    on:
      branch: develop
